apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nullserv-application-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            namespace: dev
            revision: "{{ .Values.revisions.dev }}"
          - name: staging
            namespace: staging
            revision: "{{ .Values.revisions.staging }}"
          - name: production
            namespace: production
            revision: "{{ .Values.revisions.production }}"
  template:
    metadata:
      name: '{{name}}-nullserv-application'
    spec:
      project: default
      source:
        repoURL: git@github.com:marthydavid/argocd-test.git
        targetRevision: '{{revision}}' # or specify a branch, tag, or commit
        path: app_of_apps/demo # Adjust this path to where your Helm chart is located in the repo
        helm:
          releaseName: 'nullserv-{{name}}'
          values: |
            name: 'nullserv-{{name}}'
            namespace: '{{namespace}}'
          valueFiles: 
            - '../../values/{{name}}/values.yaml'
            
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
