apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-demo
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: git@github.com:marthydavid/argocd-test.git
    targetRevision: HEAD
    path: app_of_apps/appset
    helm:
      valuesObject:
        revisions:
          dev: release-2.4.x
          staging: staging-2.0.1
          production: prod-2.0.1
  destination:
    server: https://mdavid-vcluster.erfk.kozpont.otp # Target cluster URL
    namespace: argocd # Target namespace
  syncPolicy:
    automated:
      selfHeal: true
      prune: true # Be cautious with this in production
    syncOptions:
      - CreateNamespace=true 